// Load files from the synthetic fixture tier (public/data). Generated by
// `make web-fixtures` — real exporter bytes over the synthetic DuckDB,
// never anything derived from the release.

import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

const TIER_ROOT = join(process.cwd(), 'public', 'data')

export function fixtureTierPresent(): boolean {
  return existsSync(join(TIER_ROOT, 'meta.json'))
}

export function readFixtureText(relative: string): string {
  const path = join(TIER_ROOT, relative)
  if (!existsSync(path)) {
    throw new Error(
      `fixture ${relative} is missing — run \`make web-fixtures\` (CI runs it before vitest)`,
    )
  }
  return readFileSync(path, 'utf8')
}

export function readFixtureJson<T>(relative: string): T {
  return JSON.parse(readFixtureText(relative)) as T
}
