/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe for Cloud Run and uptime monitoring.
         *
         *     ``status`` reports the process; ``data`` is honest about whether a
         *     DuckDB file is baked into this deployment (CI images have none).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Survey-weighted estimates with design-based CIs
         * @description One outcome at one wave, grouped and filtered. Every row carries
         *     the weight, SE method, unweighted n, CI and suppression flags; the
         *     weight itself is resolved from the wave→weight→eligibility table,
         *     never chosen here.
         */
        get: operations["aggregate_v1_aggregate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Within-person change across waves
         * @description Mean within-person change with a design-based CI, plus (for
         *     integer-coded items) the distribution of individual change and (for
         *     categorical items) the transition matrix. ``from=Y1&via=MY&to=Y2``
         *     returns the three panel legs under the three-point weight.
         */
        get: operations["change_v1_change_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/correlates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Not implemented: Phase 6
         * @description Ranked weighted associations ship in Phase 6 together with the
         *     adjusted models and the Correlates view (docs/PROPOSAL.md §7); the
         *     engine's `weighted_correlation` exists but is deliberately not served
         *     until its caveats ship with it.
         */
        get: operations["correlates_v1_correlates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate estimates as CSV
         * @description Same query model as /v1/aggregate; the response meta rides along
         *     as `#`-comment header lines, so a downloaded file still names its
         *     weight, data version and suppression rules.
         */
        get: operations["export_csv_v1_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Data version, countries, waves, weight table
         * @description Everything static a client needs: the data version behind every
         *     number, the countries, and the wave → weight → eligibility table
         *     verbatim from the engine (the only home of those rules).
         */
        get: operations["meta_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * US state-level aggregates with state weights
         * @description State-by-state estimates for US respondents with a state (157 US
         *     rows have none). ``adj=true`` uses the ``_ADJ_`` weight variants
         *     (unavailable for Wave 1, which needed no adjustment).
         */
        get: operations["states_v1_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/variables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the variable catalog */
        get: operations["list_variables_v1_variables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/variables/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One variable: wording, labels, missingness */
        get: operations["variable_detail_v1_variables__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CountryModel */
        CountryModel: {
            /** Code */
            code: number;
            /** Iso3 */
            iso3: string;
            /** Name */
            name: string;
        };
        /** EstimateResponse */
        EstimateResponse: {
            meta: components["schemas"]["ResponseMeta"];
            /** Rows */
            rows: components["schemas"]["EstimateRow"][];
        };
        /**
         * EstimateRow
         * @description One estimator record, verbatim from the engine's common record.
         *
         *     Every number ships with its weight, ``se_method``, unweighted ``n``,
         *     CI bounds and suppression flags; suppressed rows keep ``n``/``sum_w``
         *     and null the estimates. The optional key fields identify sub-rows:
         *     ``level`` (proportions/distributions), ``p`` (quantiles), ``leg``
         *     (three-point panels), ``from_level``/``to_level``/``measure``
         *     (transition matrices).
         */
        EstimateRow: {
            /** Ci Hi */
            ci_hi: number | null;
            /** Ci Level */
            ci_level: number;
            /** Ci Lo */
            ci_lo: number | null;
            /** Ci Method */
            ci_method: string;
            /** Df */
            df: number | null;
            /** Estimate */
            estimate: number | null;
            /** Flagged */
            flagged: boolean;
            /** From Level */
            from_level?: number | null;
            /** Group */
            group: {
                [key: string]: string | number | boolean | null;
            };
            /** Leg */
            leg?: string | null;
            /** Level */
            level?: number | null;
            /** Measure */
            measure?: string | null;
            /** N */
            n: number;
            /** N Psu */
            n_psu: number | null;
            /** N Strata */
            n_strata: number | null;
            /** P */
            p?: number | null;
            /** Se */
            se: number | null;
            /** Se Method */
            se_method: string;
            /** Stat */
            stat: string;
            /** Sum W */
            sum_w: number;
            /** Suppressed */
            suppressed: boolean;
            /** To Level */
            to_level?: number | null;
            /** Weight */
            weight: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness + build + data identity (`data` is honest: absent in CI images).
         */
        HealthResponse: {
            /** Data */
            data: string;
            /** Data Version */
            data_version: string | null;
            /** Git Sha */
            git_sha: string | null;
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** MetaResponse */
        MetaResponse: {
            /** Breakdowns */
            breakdowns: string[];
            /** Ci Level */
            ci_level: number;
            /** Countries */
            countries: components["schemas"]["CountryModel"][];
            /** Data Version */
            data_version: string | null;
            /** Families */
            families: string[];
            /** Git Sha */
            git_sha: string | null;
            suppression: components["schemas"]["SuppressionModel"];
            /** Waves */
            waves: string[];
            /** Weight Table */
            weight_table: components["schemas"]["WeightSpecModel"][];
        };
        /**
         * MissingnessRow
         * @description Response coverage per wave × country (from the pipeline's `coverage`).
         */
        MissingnessRow: {
            /** Country Code */
            country_code: number;
            /** N Dk */
            n_dk: number;
            /** N Present */
            n_present: number;
            /** N Refused */
            n_refused: number;
            /** N Skipped */
            n_skipped: number;
            /** N Valid */
            n_valid: number;
            /** Wave */
            wave: string;
        };
        /**
         * ResponseMeta
         * @description What every estimate response says about itself (ADR-0008: the same
         *     envelope is emitted by the static exporter, so the front end never
         *     cares which tier answered).
         */
        ResponseMeta: {
            /** By */
            by: string[];
            /** Ci Level */
            ci_level: number;
            /** Data Version */
            data_version: string | null;
            /** Direction */
            direction: string;
            /** Filters */
            filters: {
                [key: string]: (string | number | boolean | null)[];
            };
            /** N Frame */
            n_frame: number;
            /** N Valid */
            n_valid: number;
            /** Oriented */
            oriented: boolean;
            /** Outcome */
            outcome: string;
            /** Scale Type */
            scale_type: string;
            /** Scope */
            scope: string;
            /** Se Method */
            se_method: string;
            /** Stat */
            stat: string;
            suppression: components["schemas"]["SuppressionModel"];
            /** Waves */
            waves: string[];
            /** Weight */
            weight: string;
            /** Weight Key */
            weight_key: string;
        };
        /** SuppressionModel */
        SuppressionModel: {
            /** Flag Below */
            flag_below: number;
            /** Threshold */
            threshold: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValueLabelModel */
        ValueLabelModel: {
            /** Code */
            code: number;
            /** Country Code */
            country_code: number | null;
            /** Is Nonresponse */
            is_nonresponse: boolean;
            /** Label */
            label: string;
            /** Wave */
            wave: string | null;
        };
        /** VariableDetail */
        VariableDetail: {
            /** Direction */
            direction: string;
            /** Display Name */
            display_name: string;
            /** Family */
            family: string;
            /** Is Country Specific */
            is_country_specific: boolean;
            /** Is Derived */
            is_derived: boolean;
            /** Label */
            label: string | null;
            /** Max */
            max: number | null;
            /** Min */
            min: number | null;
            /** Missingness */
            missingness: components["schemas"]["MissingnessRow"][];
            /** Name */
            name: string;
            /** Scale Type */
            scale_type: string;
            /** Servable */
            servable: boolean;
            /** Value Labels */
            value_labels: components["schemas"]["ValueLabelModel"][];
            /** Waves Available */
            waves_available: string[];
            /** Wording */
            wording: string | null;
        };
        /** VariableList */
        VariableList: {
            /** Variables */
            variables: components["schemas"]["VariableSummary"][];
        };
        /** VariableSummary */
        VariableSummary: {
            /** Direction */
            direction: string;
            /** Display Name */
            display_name: string;
            /** Family */
            family: string;
            /** Is Country Specific */
            is_country_specific: boolean;
            /** Is Derived */
            is_derived: boolean;
            /** Label */
            label: string | null;
            /** Max */
            max: number | null;
            /** Min */
            min: number | null;
            /** Name */
            name: string;
            /** Scale Type */
            scale_type: string;
            /** Servable */
            servable: boolean;
            /** Waves Available */
            waves_available: string[];
        };
        /**
         * WeightSpecModel
         * @description One row of the wave→weight→eligibility table, verbatim.
         */
        WeightSpecModel: {
            /** Is Default */
            is_default: boolean;
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Rationale */
            rationale: string;
            /** Requires Has Midyear */
            requires_has_midyear: boolean;
            /** Requires Midyear Type 1 */
            requires_midyear_type_1: boolean;
            /** Requires Retained Y2 */
            requires_retained_y2: boolean;
            /** Scope */
            scope: string;
            /** Waves */
            waves: string[];
            /** Weight */
            weight: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    aggregate_v1_aggregate_get: {
        parameters: {
            query: {
                outcome: string;
                wave: string;
                stat?: string;
                by?: string[] | null;
                filter?: string[] | null;
                scope?: string;
                oriented?: boolean;
                p?: number[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_v1_change_get: {
        parameters: {
            query: {
                outcome: string;
                to: string;
                via?: string | null;
                by?: string[] | null;
                filter?: string[] | null;
                scope?: string;
                rect?: boolean;
                from?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correlates_v1_correlates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    export_csv_v1_export_csv_get: {
        parameters: {
            query: {
                outcome: string;
                wave: string;
                stat?: string;
                by?: string[] | null;
                filter?: string[] | null;
                scope?: string;
                oriented?: boolean;
                p?: number[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    states_v1_states_get: {
        parameters: {
            query: {
                outcome: string;
                wave: string;
                stat?: string;
                adj?: boolean;
                oriented?: boolean;
                by?: string[] | null;
                filter?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_variables_v1_variables_get: {
        parameters: {
            query?: {
                /** @description substring of name/display name/wording */
                q?: string | null;
                /** @description filter to one family */
                family?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariableList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    variable_detail_v1_variables__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariableDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
