/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe for Cloud Run and uptime monitoring.
         *
         *     ``status`` reports the process; ``data`` is honest about whether a
         *     DuckDB file is baked into this deployment (CI images have none).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Survey-weighted estimates with design-based CIs
         * @description One outcome at one wave, grouped and filtered. Every row carries
         *     the weight, SE method, unweighted n, CI and suppression flags; the
         *     weight itself is resolved from the wave→weight→eligibility table,
         *     never chosen here.
         */
        get: operations["aggregate_v1_aggregate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Within-person change across waves
         * @description Within-person change with a design-based CI. Numeric scales (0–10,
         *     counts) report the mean change on values aligned so higher means more
         *     of what the measure names (``stat = "change"``), plus the distribution
         *     of individual change; categorical items report the change in the
         *     share answering each level (``stat = "change_share"``, a fraction —
         *     × 100 for percentage points) plus the transition matrix.
         *     ``from=Y1&via=MY&to=Y2`` returns the three panel legs under the
         *     three-point weight (numeric scales only).
         */
        get: operations["change_v1_change_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/correlates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What travels with an outcome: ranked associations
         * @description Associations, not causes. Rows are weighted Pearson or Spearman
         *     coefficients with no interval (``ci_method = "none"``). Omit
         *     ``against`` for the ranked sweep over every other servable ordered
         *     item at the wave, cut to ``limit`` predictors (ranked by the median
         *     absolute association across the groups with at least ``meta.min_n``
         *     complete cases; ``meta.n_excluded`` candidates fell below it and are
         *     not ranked). Of two kept predictors built from the same answers only
         *     the one built from more of them stays (a score over its questions; on
         *     a tie, a score over its screen-positive flag); the list backfills to
         *     ``limit`` and ``meta.dropped_overlap`` names what was left out, and
         *     what stands in for it. Binary items enter as indicators of code 1
         *     (Yes / screen positive). Global scope only.
         *
         *     ``pooled=average`` — in place of a country filter — takes each
         *     country's own correlation and their plain mean: every country counts
         *     the same, and one with no estimate (it did not ask a question) drops
         *     out. Each row's ``n`` is the complete cases summed over the countries
         *     in its average (the ranking floor reads it), ``n_countries`` counts
         *     them, and ``flagged`` says every one of them rests on fewer than
         *     ``meta.min_n`` people; ``meta.countries`` lists every country in at
         *     least one average. The dedupe is unchanged.
         *
         *     At ``wave=MY`` a midyear question reads its midyear answers and any
         *     other question the same respondents' ``other_wave`` answers (Y1 by
         *     default: every midyear respondent, ``w_l1m``; Y2: those who also did
         *     Wave 2, ``w_l1m2``); ``meta.answer_waves`` says which. A midyear
         *     outcome is ranked against every midyear question and every question
         *     asked at ``other_wave``; any other outcome against the midyear
         *     questions only. Two questions neither of which the midyear survey
         *     asked belong at their own wave: 422.
         *
         *     ``adjusted=true`` — the predictor's coefficient in a survey-weighted
         *     regression under the fixed control set (``stat = "beta"``, plus a
         *     ``beta_per_sd`` row) with a design-based CI — is disabled unless the
         *     server enables it (``FA_ADJUSTED_ENABLED``); otherwise it is a 422.
         */
        get: operations["correlates_v1_correlates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/correlations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A correlation table: every pair among 2–10 questions
         * @description Associations, not causes. Every pair i < j of the questions named,
         *     in the order named: the weighted Pearson or Spearman correlation over
         *     the people who answered both (a point estimate with no interval; the
         *     number /v1/correlates reports for the pair), its n, and ``below_min_n``
         *     when fewer than ``meta.min_n`` people answered both. A pair built from
         *     the same answers (a score and its own question) is marked
         *     ``shares_answers`` and carries no correlation — it goes together by
         *     construction. Each row's correlations are taken in one pass over the
         *     frame. Both items of every pair are aligned to their labels, so the
         *     signs are the ranked list's. ``similar_order`` lists the questions
         *     with those that go together side by side: average-linkage clustering
         *     on 1 − |r| (a pair sharing answers at 0, one with no estimate at 1),
         *     ties broken toward the order asked. ``pooled=average`` takes each
         *     pair's correlation in each country and their plain mean: each
         *     correlation's ``n_countries`` counts the countries in it, ``n`` sums
         *     their people, ``below_min_n`` says every one rests on fewer than
         *     ``meta.min_n``, and ``meta.countries`` lists every country in at least
         *     one. At ``wave=MY`` the table
         *     holds one midyear question at least; the questions the midyear survey
         *     did not ask read the same people's ``other_wave`` answers, and every
         *     pair — two such questions included — is taken on the same people.
         */
        get: operations["correlations_v1_correlations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/correlations/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Two questions side by side: a weighted cross-tab and their correlation
         * @description Both items must be ordered (a 0–10 scale, an ordered or yes/no
         *     answer, a count), asked at the wave and not built from the same
         *     answers (a score and its own question go together by construction:
         *     422). ``columns`` are x's answers (its levels: up to eleven answers,
         *     else ten equal-width bins between its weighted 1st and 99th
         *     percentiles, the end bins taking in the tails), each with the weighted
         *     share of the people who answered both who gave it; ``rows`` are y's,
         *     levelled the same way; both run from least to most of what the item's
         *     label names. ``cells`` gives, column by column, the weighted share of
         *     the column's people who gave each row's answer — every column adds to
         *     1 — and ``shares`` the same cells as estimate rows with their
         *     design-based CIs (the /v1/aggregate proportion estimator grouped by
         *     x). A cell is ``flagged`` when fewer than ``cell_flag_below`` people
         *     gave that pair of answers or its column holds fewer than
         *     ``column_flag_below`` (flagged, never withheld). ``correlation`` is the
         *     weighted Pearson or Spearman coefficient over the people who answered
         *     both — the number /v1/correlates reports for the pair, with no
         *     interval. ``pooled=average`` takes each country on its own and their
         *     plain mean: of the correlations (``correlation.n_countries`` counts
         *     the countries in it; ``flagged`` when every one rests on fewer than
         *     ``min_n`` people), of the shares who gave each of x's answers, and of
         *     each column's shares over the countries with people in that column —
         *     so every column still adds to 1 — each with SE √(Σ se²) / K and a
         *     normal interval, and ``n`` summed over the countries (the flags read
         *     it); ``shares.meta.countries`` lists the countries with people who
         *     answered both. At ``wave=MY`` one question at least must be a midyear
         *     question; the other reads its midyear answers or the same people's
         *     ``other_wave`` answers (``shares.meta.answer_waves``).
         */
        get: operations["correlation_pair_v1_correlations_pair_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate estimates as CSV
         * @description Same query model as /v1/aggregate; the response meta rides along
         *     as `#`-comment header lines, so a downloaded file still names its
         *     weight, data version and suppression rules.
         */
        get: operations["export_csv_v1_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Data version, countries, waves, weight table
         * @description Everything static a client needs: the data version behind every
         *     number, the countries, and the wave → weight → eligibility table
         *     verbatim from the engine (the only home of those rules).
         */
        get: operations["meta_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * US state-level aggregates with state weights
         * @description State-by-state estimates for US respondents with a state (157 US
         *     rows have none). ``adj=true`` uses the ``_ADJ_`` weight variants
         *     (unavailable for Wave 1, which needed no adjustment).
         */
        get: operations["states_v1_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/variables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the variable catalog */
        get: operations["list_variables_v1_variables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/variables/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One variable: wording, labels, missingness */
        get: operations["variable_detail_v1_variables__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BreakdownLabelsModel
         * @description Display name + ordered levels for one demographic breakdown column
         *     (from ``flourish_stats.breakdowns`` — the front end owns no copy).
         */
        BreakdownLabelsModel: {
            /** Display Name */
            display_name: string;
            /** Levels */
            levels: components["schemas"]["BreakdownLevelModel"][];
        };
        /** BreakdownLevelModel */
        BreakdownLevelModel: {
            /** Label */
            label: string;
            /** Value */
            value: number | string;
        };
        /**
         * ComponentModel
         * @description One question a derived score is computed from (its own catalog
         *     entry, sliced to what the Codebook renders under the score).
         */
        ComponentModel: {
            /** Display Name */
            display_name: string;
            /** Name */
            name: string;
            /** Value Labels */
            value_labels: components["schemas"]["ValueLabelModel"][];
            /** Wording */
            wording: string | null;
        };
        /**
         * CorrelationPairModel
         * @description One cell of a correlation table (/v1/correlations): the questions
         *     ``a`` and ``b``, ``a`` before ``b`` in the order they were asked for.
         */
        CorrelationPairModel: {
            /** A */
            a: string;
            /** B */
            b: string;
            /** Below Min N */
            below_min_n: boolean;
            correlation: components["schemas"]["EstimateRow"] | null;
            /** Shares Answers */
            shares_answers: boolean;
        };
        /**
         * CorrelationsMeta
         * @description What a correlation table says about itself.
         */
        CorrelationsMeta: {
            /** Answer Waves */
            answer_waves?: {
                [key: string]: string;
            } | null;
            /** Ci Level */
            ci_level: number;
            /** Countries */
            countries?: number[] | null;
            /** Data Version */
            data_version: string | null;
            /** Filters */
            filters: {
                [key: string]: (string | number | boolean | null)[];
            };
            /** Min N */
            min_n: number;
            /** N Frame */
            n_frame: number;
            /** Other Wave */
            other_wave?: string | null;
            /** Pooled */
            pooled?: string | null;
            /** Stat */
            stat: string;
            suppression: components["schemas"]["SuppressionModel"];
            /** Vars */
            vars: string[];
            /** Wave */
            wave: string;
            /** Weight */
            weight: string;
            /** Weight Key */
            weight_key: string;
        };
        /**
         * CorrelationsResponse
         * @description Every pair of 2–10 questions in one country (/v1/correlations).
         */
        CorrelationsResponse: {
            meta: components["schemas"]["CorrelationsMeta"];
            /** Pairs */
            pairs: components["schemas"]["CorrelationPairModel"][];
            /** Similar Order */
            similar_order: string[];
        };
        /** CountryModel */
        CountryModel: {
            /** Code */
            code: number;
            /** Iso3 */
            iso3: string;
            /** Name */
            name: string;
        };
        /** EstimateResponse */
        EstimateResponse: {
            meta: components["schemas"]["ResponseMeta"];
            /** Rows */
            rows: components["schemas"]["EstimateRow"][];
        };
        /**
         * EstimateRow
         * @description One estimator record, verbatim from the engine's common record.
         *
         *     Every number ships with its weight, ``se_method``, unweighted ``n``,
         *     CI bounds and suppression flags; suppressed rows keep ``n``/``sum_w``
         *     and null the estimates. The optional key fields identify sub-rows:
         *     ``level`` (proportions/distributions), ``p`` (quantiles), ``leg``
         *     (three-point panels), ``from_level``/``to_level``/``measure``
         *     (transition matrices; also the ``beta``/``beta_per_sd`` rows of an
         *     adjusted association) and ``predictor`` (the item an association is
         *     taken against, /v1/correlates).
         */
        EstimateRow: {
            /** Ci Hi */
            ci_hi: number | null;
            /** Ci Level */
            ci_level: number;
            /** Ci Lo */
            ci_lo: number | null;
            /** Ci Method */
            ci_method: string;
            /** Df */
            df: number | null;
            /** Estimate */
            estimate: number | null;
            /** Flagged */
            flagged: boolean;
            /** From Level */
            from_level?: number | null;
            /** Group */
            group: {
                [key: string]: string | number | boolean | null;
            };
            /** Leg */
            leg?: string | null;
            /** Level */
            level?: number | null;
            /** Measure */
            measure?: string | null;
            /** N */
            n: number;
            /** N Countries */
            n_countries?: number | null;
            /** N Psu */
            n_psu: number | null;
            /** N Strata */
            n_strata: number | null;
            /** P */
            p?: number | null;
            /** Predictor */
            predictor?: string | null;
            /** Se */
            se: number | null;
            /** Se Method */
            se_method: string;
            /** Stat */
            stat: string;
            /** Sum W */
            sum_w: number;
            /** Suppressed */
            suppressed: boolean;
            /** To Level */
            to_level?: number | null;
            /** Weight */
            weight: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness + build + data identity (`data` is honest: absent in CI images).
         */
        HealthResponse: {
            /** Data */
            data: string;
            /** Data Version */
            data_version: string | null;
            /** Git Sha */
            git_sha: string | null;
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** MetaResponse */
        MetaResponse: {
            /** Breakdown Labels */
            breakdown_labels: {
                [key: string]: components["schemas"]["BreakdownLabelsModel"];
            };
            /** Breakdowns */
            breakdowns: string[];
            /** Ci Level */
            ci_level: number;
            /** Countries */
            countries: components["schemas"]["CountryModel"][];
            /** Data Version */
            data_version: string | null;
            /** Families */
            families: string[];
            /** Git Sha */
            git_sha?: string | null;
            /** State Labels */
            state_labels: {
                [key: string]: components["schemas"]["StateLabelModel"];
            };
            suppression: components["schemas"]["SuppressionModel"];
            /** Waves */
            waves: string[];
            /** Weight Table */
            weight_table: components["schemas"]["WeightSpecModel"][];
        };
        /**
         * MissingnessRow
         * @description Response coverage per wave × country (from the pipeline's `coverage`).
         */
        MissingnessRow: {
            /** Country Code */
            country_code: number;
            /** N Dk */
            n_dk: number;
            /** N Present */
            n_present: number;
            /** N Refused */
            n_refused: number;
            /** N Skipped */
            n_skipped: number;
            /** N Valid */
            n_valid: number;
            /** Wave */
            wave: string;
        };
        /**
         * PairCellModel
         * @description One pair of answers: of the people who gave x the column's answer,
         *     the weighted share who gave y the row's (each column adds to 1).
         */
        PairCellModel: {
            /** Flagged */
            flagged: boolean;
            /** N */
            n: number;
            /** Share */
            share: number | null;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * PairColumnModel
         * @description One of x's answers: the weighted share of the people who answered
         *     both questions who gave it, with its interval (the /v1/aggregate
         *     proportion estimator).
         */
        PairColumnModel: {
            /** Ci Hi */
            ci_hi: number | null;
            /** Ci Lo */
            ci_lo: number | null;
            /** Code */
            code: number;
            /** Flagged */
            flagged: boolean;
            /** Label */
            label: string;
            /** N */
            n: number;
            /** Share */
            share: number;
        };
        /**
         * PairLevelModel
         * @description One answer of either question in a cross-tab (/v1/correlations/pair),
         *     or one equal-width bin of a long scale.
         */
        PairLevelModel: {
            /** Code */
            code: number;
            /** Label */
            label: string;
        };
        /**
         * PairResponse
         * @description Two questions side by side (/v1/correlations/pair): a weighted
         *     cross-tab of their answers — each column one of x's answers, each
         *     cell the share of that column who gave the row's answer to y — the
         *     share of people who gave each of x's answers, and the two questions'
         *     weighted correlation. Both axes run in their question's aligned order
         *     (least to most of what its label names, ADR-0015); respondent-level
         *     answers are never served.
         */
        PairResponse: {
            /** Cell Flag Below */
            cell_flag_below: number;
            /** Cells */
            cells: components["schemas"]["PairCellModel"][];
            /** Column Flag Below */
            column_flag_below: number;
            /** Columns */
            columns: components["schemas"]["PairColumnModel"][];
            correlation: components["schemas"]["EstimateRow"];
            /** Min N */
            min_n: number;
            /** Rows */
            rows: components["schemas"]["PairLevelModel"][];
            shares: components["schemas"]["EstimateResponse"];
            /** X */
            x: string;
            /** X Grouping */
            x_grouping: string;
            /** Y */
            y: string;
            /** Y Grouping */
            y_grouping: string;
        };
        /**
         * ResponseMeta
         * @description What every estimate response says about itself (ADR-0008: the same
         *     envelope is emitted by the static exporter, so the front end never
         *     cares which tier answered).
         */
        ResponseMeta: {
            /** Adjusted */
            adjusted?: boolean | null;
            /** Answer Waves */
            answer_waves?: {
                [key: string]: string;
            } | null;
            /** By */
            by: string[];
            /** Ci Level */
            ci_level: number;
            /** Controls */
            controls?: string[] | null;
            /** Countries */
            countries?: number[] | null;
            /** Data Version */
            data_version: string | null;
            /** Direction */
            direction: string;
            /** Dropped Overlap */
            dropped_overlap?: {
                [key: string]: string;
            } | null;
            /** Filters */
            filters: {
                [key: string]: (string | number | boolean | null)[];
            };
            /** Min N */
            min_n?: number | null;
            /** Model */
            model?: string | null;
            /** N Excluded */
            n_excluded?: number | null;
            /** N Frame */
            n_frame: number;
            /** N Valid */
            n_valid: number;
            /** Oriented */
            oriented: boolean;
            /** Other Wave */
            other_wave?: string | null;
            /** Outcome */
            outcome: string;
            /** Pooled */
            pooled?: string | null;
            /** Scale Type */
            scale_type: string;
            /** Scope */
            scope: string;
            /** Se Method */
            se_method: string;
            /** Stat */
            stat: string;
            suppression: components["schemas"]["SuppressionModel"];
            /** Waves */
            waves: string[];
            /** Weight */
            weight: string;
            /** Weight Key */
            weight_key: string;
        };
        /**
         * StateLabelModel
         * @description A US state code's display name and member states (a pooled group
         *     of small states lists several; ``flourish_stats.states``).
         */
        StateLabelModel: {
            /** Members */
            members: string[];
            /** Name */
            name: string;
        };
        /** SuppressionModel */
        SuppressionModel: {
            /** Flag Below */
            flag_below: number;
            /** Threshold */
            threshold: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValueLabelModel */
        ValueLabelModel: {
            /** Code */
            code: number;
            /** Country Code */
            country_code: number | null;
            /** Is Nonresponse */
            is_nonresponse: boolean;
            /** Label */
            label: string;
            /** Wave */
            wave: string | null;
        };
        /** VariableDetail */
        VariableDetail: {
            /**
             * Components
             * @default []
             */
            components: components["schemas"]["ComponentModel"][];
            /** Default Stat */
            default_stat: string;
            /** Direction */
            direction: string;
            /** Display Name */
            display_name: string;
            /** Family */
            family: string;
            /** Is Country Specific */
            is_country_specific: boolean;
            /** Is Derived */
            is_derived: boolean;
            /** Label */
            label: string | null;
            /** Max */
            max: number | null;
            /** Min */
            min: number | null;
            /** Missingness */
            missingness: components["schemas"]["MissingnessRow"][];
            /** Name */
            name: string;
            /** Polarity */
            polarity: string;
            /** Scale Type */
            scale_type: string;
            /** Scoring */
            scoring?: string | null;
            /** Servable */
            servable: boolean;
            /** Subfamily */
            subfamily: string | null;
            /** Value Labels */
            value_labels: components["schemas"]["ValueLabelModel"][];
            /** Waves Available */
            waves_available: string[];
            /** Wording */
            wording: string | null;
        };
        /** VariableList */
        VariableList: {
            /** Variables */
            variables: components["schemas"]["VariableSummary"][];
        };
        /** VariableSummary */
        VariableSummary: {
            /** Default Stat */
            default_stat: string;
            /** Direction */
            direction: string;
            /** Display Name */
            display_name: string;
            /** Family */
            family: string;
            /** Is Country Specific */
            is_country_specific: boolean;
            /** Is Derived */
            is_derived: boolean;
            /** Label */
            label: string | null;
            /** Max */
            max: number | null;
            /** Min */
            min: number | null;
            /** Name */
            name: string;
            /** Polarity */
            polarity: string;
            /** Scale Type */
            scale_type: string;
            /** Servable */
            servable: boolean;
            /** Subfamily */
            subfamily: string | null;
            /** Waves Available */
            waves_available: string[];
            /** Wording */
            wording: string | null;
        };
        /**
         * WeightSpecModel
         * @description One row of the wave→weight→eligibility table, verbatim.
         */
        WeightSpecModel: {
            /** Is Default */
            is_default: boolean;
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Rationale */
            rationale: string;
            /** Requires Has Midyear */
            requires_has_midyear: boolean;
            /** Requires Midyear Type 1 */
            requires_midyear_type_1: boolean;
            /** Requires Retained Y2 */
            requires_retained_y2: boolean;
            /** Scope */
            scope: string;
            /** State Column */
            state_column?: string | null;
            /** Waves */
            waves: string[];
            /** Weight */
            weight: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    aggregate_v1_aggregate_get: {
        parameters: {
            query: {
                outcome: string;
                wave: string;
                stat?: string;
                by?: string[] | null;
                filter?: string[] | null;
                scope?: string;
                oriented?: boolean;
                p?: number[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_v1_change_get: {
        parameters: {
            query: {
                outcome: string;
                to: string;
                via?: string | null;
                by?: string[] | null;
                filter?: string[] | null;
                scope?: string;
                rect?: boolean;
                from?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correlates_v1_correlates_get: {
        parameters: {
            query: {
                outcome: string;
                wave: string;
                against?: string[] | null;
                method?: string;
                by?: string[] | null;
                filter?: string[] | null;
                limit?: number;
                /** @description average: each country's own estimate, and their plain average — every country counts the same (ADR-0020) — in place of a country filter. */
                pooled?: string | null;
                /** @description At wave=MY: Y1 (default) or Y2 — the wave every question the midyear survey did not ask reads the same people's answers from (ADR-0020). */
                other_wave?: string | null;
                /** @description The adjusted associations under the fixed control set (ADR-0014) instead of plain correlations — disabled unless the server enables it (FA_ADJUSTED_ENABLED); otherwise a 422. */
                adjusted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correlations_v1_correlations_get: {
        parameters: {
            query: {
                /** @description 2 to 10 ordered questions asked at the wave, repeatable, in table order. */
                vars: string[];
                wave: string;
                /** @description Exactly one country_code:N (none when pooled), plus optional demographic domains. */
                filter?: string[] | null;
                /** @description pearson (default) or spearman. */
                method?: string;
                /** @description average: each country's own correlations, and their plain average (ADR-0020), in place of the country filter. */
                pooled?: string | null;
                /** @description At wave=MY: Y1 (default) or Y2 — as /v1/correlates (ADR-0020). */
                other_wave?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correlation_pair_v1_correlations_pair_get: {
        parameters: {
            query: {
                /** @description The question on the rows. */
                y: string;
                /** @description The question on the columns. */
                x: string;
                wave: string;
                /** @description Exactly one country_code:N (none when pooled), plus optional demographic domains. */
                filter?: string[] | null;
                /** @description pearson (default) or spearman. */
                method?: string;
                /** @description average: each country's own cross-tab and correlation, and their plain average (ADR-0020), in place of the country filter. */
                pooled?: string | null;
                /** @description At wave=MY: Y1 (default) or Y2 — as /v1/correlates (ADR-0020). */
                other_wave?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_v1_export_csv_get: {
        parameters: {
            query: {
                outcome: string;
                wave: string;
                stat?: string;
                by?: string[] | null;
                filter?: string[] | null;
                scope?: string;
                oriented?: boolean;
                p?: number[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    states_v1_states_get: {
        parameters: {
            query: {
                outcome: string;
                wave: string;
                stat?: string;
                adj?: boolean;
                oriented?: boolean;
                by?: string[] | null;
                filter?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_variables_v1_variables_get: {
        parameters: {
            query?: {
                /** @description substring of name/display name/wording */
                q?: string | null;
                /** @description filter to one family */
                family?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariableList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    variable_detail_v1_variables__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariableDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
