/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe for Cloud Run and uptime monitoring.
         *
         *     ``status`` reports the process; ``data`` is honest about whether a
         *     DuckDB file is baked into this deployment (CI images have none).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Survey-weighted estimates with design-based CIs
         * @description One outcome at one wave, grouped and filtered. Every row carries
         *     the weight, SE method, unweighted n, CI and suppression flags; the
         *     weight itself is resolved from the wave→weight→eligibility table,
         *     never chosen here.
         */
        get: operations["aggregate_v1_aggregate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Within-person change across waves
         * @description Within-person change with a design-based CI. Numeric scales (0–10,
         *     counts) report the mean change on values aligned so higher means more
         *     of what the measure names (``stat = "change"``), plus the distribution
         *     of individual change; categorical items report the change in the
         *     share answering each level (``stat = "change_share"``, a fraction —
         *     × 100 for percentage points) plus the transition matrix.
         *     ``from=Y1&via=MY&to=Y2`` returns the three panel legs under the
         *     three-point weight (numeric scales only).
         */
        get: operations["change_v1_change_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/correlates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What travels with an outcome: ranked associations
         * @description Associations, not causes. Rows are weighted Pearson or Spearman
         *     coefficients with no interval (``ci_method = "none"``). Omit
         *     ``against`` for the ranked sweep over every other servable ordered
         *     item at the wave, cut to ``limit`` predictors (ranked by the median
         *     absolute association across the groups with at least ``meta.min_n``
         *     complete cases; ``meta.n_excluded`` candidates fell below it and are
         *     not ranked). Of two kept predictors built from the same answers only
         *     the one built from more of them stays (a score over its questions; on
         *     a tie, a score over its screen-positive flag); the list backfills to
         *     ``limit`` and ``meta.dropped_overlap`` names what was left out, and
         *     what stands in for it. Binary items enter as indicators of code 1
         *     (Yes / screen positive). Global scope only.
         *
         *     ``adjusted=true`` — the predictor's coefficient in a survey-weighted
         *     regression under the fixed control set (``stat = "beta"``, plus a
         *     ``beta_per_sd`` row) with a design-based CI — is disabled unless the
         *     server enables it (``FA_ADJUSTED_ENABLED``); otherwise it is a 422.
         */
        get: operations["correlates_v1_correlates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/correlations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A correlation table: every pair among 2–10 questions
         * @description Associations, not causes. Every pair i < j of the questions named,
         *     in the order named: the weighted Pearson or Spearman correlation over
         *     the people who answered both (a point estimate with no interval; the
         *     number /v1/correlates reports for the pair), its n, and ``below_min_n``
         *     when fewer than ``meta.min_n`` people answered both. A pair built from
         *     the same answers (a score and its own question) is marked
         *     ``shares_answers`` and carries no correlation — it goes together by
         *     construction. Each row's correlations are taken in one pass over the
         *     frame. Both items of every pair are aligned to their labels, so the
         *     signs are the ranked list's.
         */
        get: operations["correlations_v1_correlations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/correlations/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Two questions side by side: their correlation and Y's mean by X
         * @description Associations, not causes. Both items must be ordered (a 0–10 scale,
         *     an ordered or yes/no answer, a count) and asked at the wave, and must
         *     not be built from the same answers (a score and its own question go
         *     together by construction: 422). ``correlation`` is the weighted
         *     Pearson or Spearman coefficient over the people who answered both —
         *     the same number /v1/correlates reports for the pair, with no interval.
         *     ``means`` is y's weighted mean in each group of x with its
         *     design-based CI (the /v1/aggregate estimator, ``by = [x]``); a yes/no
         *     y is its share answering yes. x's groups are its answers when it has
         *     at most eleven, else equal-width bins between its weighted 1st and
         *     99th percentiles (whole-number-wide for an item counted in whole
         *     numbers), the end bins taking in the tails; they run from least to
         *     most of what x's label names, so a positive correlation slopes up.
         *     ``groups`` carries each group's label, its weighted share of those
         *     people, and whether fewer than ``means.meta.min_n`` of them are in it
         *     (flagged, never dropped).
         */
        get: operations["correlation_pair_v1_correlations_pair_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate estimates as CSV
         * @description Same query model as /v1/aggregate; the response meta rides along
         *     as `#`-comment header lines, so a downloaded file still names its
         *     weight, data version and suppression rules.
         */
        get: operations["export_csv_v1_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Data version, countries, waves, weight table
         * @description Everything static a client needs: the data version behind every
         *     number, the countries, and the wave → weight → eligibility table
         *     verbatim from the engine (the only home of those rules).
         */
        get: operations["meta_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * US state-level aggregates with state weights
         * @description State-by-state estimates for US respondents with a state (157 US
         *     rows have none). ``adj=true`` uses the ``_ADJ_`` weight variants
         *     (unavailable for Wave 1, which needed no adjustment).
         */
        get: operations["states_v1_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/variables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the variable catalog */
        get: operations["list_variables_v1_variables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/variables/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One variable: wording, labels, missingness */
        get: operations["variable_detail_v1_variables__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BreakdownLabelsModel
         * @description Display name + ordered levels for one demographic breakdown column
         *     (from ``flourish_stats.breakdowns`` — the front end owns no copy).
         */
        BreakdownLabelsModel: {
            /** Display Name */
            display_name: string;
            /** Levels */
            levels: components["schemas"]["BreakdownLevelModel"][];
        };
        /** BreakdownLevelModel */
        BreakdownLevelModel: {
            /** Label */
            label: string;
            /** Value */
            value: number | string;
        };
        /**
         * ComponentModel
         * @description One question a derived score is computed from (its own catalog
         *     entry, sliced to what the Codebook renders under the score).
         */
        ComponentModel: {
            /** Display Name */
            display_name: string;
            /** Name */
            name: string;
            /** Value Labels */
            value_labels: components["schemas"]["ValueLabelModel"][];
            /** Wording */
            wording: string | null;
        };
        /**
         * CorrelationPairModel
         * @description One cell of a correlation table (/v1/correlations): the questions
         *     ``a`` and ``b``, ``a`` before ``b`` in the order they were asked for.
         */
        CorrelationPairModel: {
            /** A */
            a: string;
            /** B */
            b: string;
            /** Below Min N */
            below_min_n: boolean;
            correlation: components["schemas"]["EstimateRow"] | null;
            /** Shares Answers */
            shares_answers: boolean;
        };
        /**
         * CorrelationsMeta
         * @description What a correlation table says about itself.
         */
        CorrelationsMeta: {
            /** Ci Level */
            ci_level: number;
            /** Data Version */
            data_version: string | null;
            /** Filters */
            filters: {
                [key: string]: (string | number | boolean | null)[];
            };
            /** Min N */
            min_n: number;
            /** N Frame */
            n_frame: number;
            /** Stat */
            stat: string;
            suppression: components["schemas"]["SuppressionModel"];
            /** Vars */
            vars: string[];
            /** Wave */
            wave: string;
            /** Weight */
            weight: string;
            /** Weight Key */
            weight_key: string;
        };
        /**
         * CorrelationsResponse
         * @description Every pair of 2–10 questions in one country (/v1/correlations).
         */
        CorrelationsResponse: {
            meta: components["schemas"]["CorrelationsMeta"];
            /** Pairs */
            pairs: components["schemas"]["CorrelationPairModel"][];
        };
        /** CountryModel */
        CountryModel: {
            /** Code */
            code: number;
            /** Iso3 */
            iso3: string;
            /** Name */
            name: string;
        };
        /** EstimateResponse */
        EstimateResponse: {
            meta: components["schemas"]["ResponseMeta"];
            /** Rows */
            rows: components["schemas"]["EstimateRow"][];
        };
        /**
         * EstimateRow
         * @description One estimator record, verbatim from the engine's common record.
         *
         *     Every number ships with its weight, ``se_method``, unweighted ``n``,
         *     CI bounds and suppression flags; suppressed rows keep ``n``/``sum_w``
         *     and null the estimates. The optional key fields identify sub-rows:
         *     ``level`` (proportions/distributions), ``p`` (quantiles), ``leg``
         *     (three-point panels), ``from_level``/``to_level``/``measure``
         *     (transition matrices; also the ``beta``/``beta_per_sd`` rows of an
         *     adjusted association) and ``predictor`` (the item an association is
         *     taken against, /v1/correlates).
         */
        EstimateRow: {
            /** Ci Hi */
            ci_hi: number | null;
            /** Ci Level */
            ci_level: number;
            /** Ci Lo */
            ci_lo: number | null;
            /** Ci Method */
            ci_method: string;
            /** Df */
            df: number | null;
            /** Estimate */
            estimate: number | null;
            /** Flagged */
            flagged: boolean;
            /** From Level */
            from_level?: number | null;
            /** Group */
            group: {
                [key: string]: string | number | boolean | null;
            };
            /** Leg */
            leg?: string | null;
            /** Level */
            level?: number | null;
            /** Measure */
            measure?: string | null;
            /** N */
            n: number;
            /** N Psu */
            n_psu: number | null;
            /** N Strata */
            n_strata: number | null;
            /** P */
            p?: number | null;
            /** Predictor */
            predictor?: string | null;
            /** Se */
            se: number | null;
            /** Se Method */
            se_method: string;
            /** Stat */
            stat: string;
            /** Sum W */
            sum_w: number;
            /** Suppressed */
            suppressed: boolean;
            /** To Level */
            to_level?: number | null;
            /** Weight */
            weight: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness + build + data identity (`data` is honest: absent in CI images).
         */
        HealthResponse: {
            /** Data */
            data: string;
            /** Data Version */
            data_version: string | null;
            /** Git Sha */
            git_sha: string | null;
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** MetaResponse */
        MetaResponse: {
            /** Breakdown Labels */
            breakdown_labels: {
                [key: string]: components["schemas"]["BreakdownLabelsModel"];
            };
            /** Breakdowns */
            breakdowns: string[];
            /** Ci Level */
            ci_level: number;
            /** Countries */
            countries: components["schemas"]["CountryModel"][];
            /** Data Version */
            data_version: string | null;
            /** Families */
            families: string[];
            /** Git Sha */
            git_sha?: string | null;
            /** State Labels */
            state_labels: {
                [key: string]: components["schemas"]["StateLabelModel"];
            };
            suppression: components["schemas"]["SuppressionModel"];
            /** Waves */
            waves: string[];
            /** Weight Table */
            weight_table: components["schemas"]["WeightSpecModel"][];
        };
        /**
         * MissingnessRow
         * @description Response coverage per wave × country (from the pipeline's `coverage`).
         */
        MissingnessRow: {
            /** Country Code */
            country_code: number;
            /** N Dk */
            n_dk: number;
            /** N Present */
            n_present: number;
            /** N Refused */
            n_refused: number;
            /** N Skipped */
            n_skipped: number;
            /** N Valid */
            n_valid: number;
            /** Wave */
            wave: string;
        };
        /**
         * PairGroupModel
         * @description One group of the compared question X (/v1/correlations/pair): one
         *     of its answers, or an equal-width bin of a long scale.
         */
        PairGroupModel: {
            /** Below Min N */
            below_min_n: boolean;
            /** Code */
            code: number;
            /** Label */
            label: string;
            /** Share */
            share: number;
        };
        /**
         * PairResponse
         * @description Two questions side by side (/v1/correlations/pair): their weighted
         *     correlation, and the outcome Y's weighted mean in each group of X —
         *     the /v1/aggregate estimator, grouped by X. Groups run in X's aligned
         *     order (from least to most of what its label names), so a positive
         *     correlation slopes up; respondent-level points are never served.
         */
        PairResponse: {
            correlation: components["schemas"]["EstimateRow"];
            /** Grouping */
            grouping: string;
            /** Groups */
            groups: components["schemas"]["PairGroupModel"][];
            means: components["schemas"]["EstimateResponse"];
            /** X */
            x: string;
        };
        /**
         * ResponseMeta
         * @description What every estimate response says about itself (ADR-0008: the same
         *     envelope is emitted by the static exporter, so the front end never
         *     cares which tier answered).
         */
        ResponseMeta: {
            /** Adjusted */
            adjusted?: boolean | null;
            /** By */
            by: string[];
            /** Ci Level */
            ci_level: number;
            /** Controls */
            controls?: string[] | null;
            /** Data Version */
            data_version: string | null;
            /** Direction */
            direction: string;
            /** Dropped Overlap */
            dropped_overlap?: {
                [key: string]: string;
            } | null;
            /** Filters */
            filters: {
                [key: string]: (string | number | boolean | null)[];
            };
            /** Min N */
            min_n?: number | null;
            /** Model */
            model?: string | null;
            /** N Excluded */
            n_excluded?: number | null;
            /** N Frame */
            n_frame: number;
            /** N Valid */
            n_valid: number;
            /** Oriented */
            oriented: boolean;
            /** Outcome */
            outcome: string;
            /** Scale Type */
            scale_type: string;
            /** Scope */
            scope: string;
            /** Se Method */
            se_method: string;
            /** Stat */
            stat: string;
            suppression: components["schemas"]["SuppressionModel"];
            /** Waves */
            waves: string[];
            /** Weight */
            weight: string;
            /** Weight Key */
            weight_key: string;
        };
        /**
         * StateLabelModel
         * @description A US state code's display name and member states (a pooled group
         *     of small states lists several; ``flourish_stats.states``).
         */
        StateLabelModel: {
            /** Members */
            members: string[];
            /** Name */
            name: string;
        };
        /** SuppressionModel */
        SuppressionModel: {
            /** Flag Below */
            flag_below: number;
            /** Threshold */
            threshold: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValueLabelModel */
        ValueLabelModel: {
            /** Code */
            code: number;
            /** Country Code */
            country_code: number | null;
            /** Is Nonresponse */
            is_nonresponse: boolean;
            /** Label */
            label: string;
            /** Wave */
            wave: string | null;
        };
        /** VariableDetail */
        VariableDetail: {
            /**
             * Components
             * @default []
             */
            components: components["schemas"]["ComponentModel"][];
            /** Default Stat */
            default_stat: string;
            /** Direction */
            direction: string;
            /** Display Name */
            display_name: string;
            /** Family */
            family: string;
            /** Is Country Specific */
            is_country_specific: boolean;
            /** Is Derived */
            is_derived: boolean;
            /** Label */
            label: string | null;
            /** Max */
            max: number | null;
            /** Min */
            min: number | null;
            /** Missingness */
            missingness: components["schemas"]["MissingnessRow"][];
            /** Name */
            name: string;
            /** Polarity */
            polarity: string;
            /** Scale Type */
            scale_type: string;
            /** Scoring */
            scoring?: string | null;
            /** Servable */
            servable: boolean;
            /** Subfamily */
            subfamily: string | null;
            /** Value Labels */
            value_labels: components["schemas"]["ValueLabelModel"][];
            /** Waves Available */
            waves_available: string[];
            /** Wording */
            wording: string | null;
        };
        /** VariableList */
        VariableList: {
            /** Variables */
            variables: components["schemas"]["VariableSummary"][];
        };
        /** VariableSummary */
        VariableSummary: {
            /** Default Stat */
            default_stat: string;
            /** Direction */
            direction: string;
            /** Display Name */
            display_name: string;
            /** Family */
            family: string;
            /** Is Country Specific */
            is_country_specific: boolean;
            /** Is Derived */
            is_derived: boolean;
            /** Label */
            label: string | null;
            /** Max */
            max: number | null;
            /** Min */
            min: number | null;
            /** Name */
            name: string;
            /** Polarity */
            polarity: string;
            /** Scale Type */
            scale_type: string;
            /** Servable */
            servable: boolean;
            /** Subfamily */
            subfamily: string | null;
            /** Waves Available */
            waves_available: string[];
            /** Wording */
            wording: string | null;
        };
        /**
         * WeightSpecModel
         * @description One row of the wave→weight→eligibility table, verbatim.
         */
        WeightSpecModel: {
            /** Is Default */
            is_default: boolean;
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Rationale */
            rationale: string;
            /** Requires Has Midyear */
            requires_has_midyear: boolean;
            /** Requires Midyear Type 1 */
            requires_midyear_type_1: boolean;
            /** Requires Retained Y2 */
            requires_retained_y2: boolean;
            /** Scope */
            scope: string;
            /** State Column */
            state_column?: string | null;
            /** Waves */
            waves: string[];
            /** Weight */
            weight: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    aggregate_v1_aggregate_get: {
        parameters: {
            query: {
                outcome: string;
                wave: string;
                stat?: string;
                by?: string[] | null;
                filter?: string[] | null;
                scope?: string;
                oriented?: boolean;
                p?: number[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_v1_change_get: {
        parameters: {
            query: {
                outcome: string;
                to: string;
                via?: string | null;
                by?: string[] | null;
                filter?: string[] | null;
                scope?: string;
                rect?: boolean;
                from?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correlates_v1_correlates_get: {
        parameters: {
            query: {
                outcome: string;
                wave: string;
                against?: string[] | null;
                method?: string;
                by?: string[] | null;
                filter?: string[] | null;
                limit?: number;
                /** @description The adjusted associations under the fixed control set (ADR-0014) instead of plain correlations — disabled unless the server enables it (FA_ADJUSTED_ENABLED); otherwise a 422. */
                adjusted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correlations_v1_correlations_get: {
        parameters: {
            query: {
                /** @description 2 to 10 ordered questions asked at the wave, repeatable, in table order. */
                vars: string[];
                wave: string;
                /** @description Exactly one country_code:N, plus optional demographic domains. */
                filter?: string[] | null;
                /** @description pearson (default) or spearman. */
                method?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correlation_pair_v1_correlations_pair_get: {
        parameters: {
            query: {
                /** @description The outcome: its weighted mean is taken per group of x. */
                y: string;
                /** @description The question compared with: its answers (or bins) group y. */
                x: string;
                wave: string;
                /** @description Exactly one country_code:N, plus optional demographic domains. */
                filter?: string[] | null;
                /** @description pearson (default) or spearman. */
                method?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_v1_export_csv_get: {
        parameters: {
            query: {
                outcome: string;
                wave: string;
                stat?: string;
                by?: string[] | null;
                filter?: string[] | null;
                scope?: string;
                oriented?: boolean;
                p?: number[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    states_v1_states_get: {
        parameters: {
            query: {
                outcome: string;
                wave: string;
                stat?: string;
                adj?: boolean;
                oriented?: boolean;
                by?: string[] | null;
                filter?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_variables_v1_variables_get: {
        parameters: {
            query?: {
                /** @description substring of name/display name/wording */
                q?: string | null;
                /** @description filter to one family */
                family?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariableList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    variable_detail_v1_variables__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariableDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
